
/* eslint-disable @typescript-eslint/no-namespace */

// 
// Generated by @himenon/openapi-typescript-code-generator v0.18.3
// 
// OpenApi : 3.0.0
// 
// 


export namespace Schemas {
    /** 値段の情報のmodel */
    export interface Price {
        /** 割引後の販売価格 */
        selling_price: number;
        /** 元の値段 */
        original_price: number;
        /** 割引が適応されているか */
        discounted: boolean;
        /** 割引の総量 */
        discount_amount: number;
        /** 割引の割合(0-100[%]) */
        discount_percentage: number;
    }
    /** ショップアイテムのmodel */
    export interface ShopItem {
        /** id */
        id: string;
        /** 商品の名前 */
        name: string;
        /** 商品のサムネイル画像のURL */
        thumbnail: string;
        price: Schemas.Price;
        /** タグの配列 */
        tags: Schemas.Tag[];
        /** カテゴリの配列 */
        categories: Schemas.Category[];
        /** キャンペーンの配列 */
        campaigns: Schemas.Campaign[];
    }
    /** 商品の詳細情報のmodel */
    export interface ShopItemDetail {
        /** id */
        id: string;
        /** 商品の名前 */
        name: string;
        /** サムネイル画像のURL */
        thumbnail: string;
        price: Schemas.Price;
        /** タグの配列 */
        tags: Schemas.Tag[];
        /** カテゴリのの配列 */
        categories: Schemas.Category[];
        /** キャンペーンの配列 */
        campaigns: Schemas.Campaign[];
        /** 商品の詳細 */
        details: Schemas.DetailContent[];
        /** 画像のURLの配列 */
        images: string[];
        /** 関連商品の配列 */
        related_shop_items: Schemas.ShopItem[];
    }
    export interface DetailContent {
        /** ヘッダー */
        header: string;
        /** 内容 */
        content: string;
    }
    /** カテゴリのmodel */
    export interface Category {
        /** id */
        id: string;
        /** カテゴリの名前 */
        name: string;
        /** カテゴリのサムネイル画像のURL */
        thumbnail: string;
    }
    export interface Campaign {
        /** id */
        id: string;
        /** キャンペーンの名前 */
        name: string;
        /** キャンペーンのサムネイル画像のURL */
        thumbnail: string;
    }
    export interface Promotion {
        /** id */
        id: string;
        /** プロモーションのタイトル */
        title: string;
        /** プロモーションの画像のURL */
        image: string;
        /** プロモーションの詳細 */
        detail: string;
        /** プロモーションのリンクのURL */
        link: string;
    }
    /** お知らせのmodel */
    export interface Information {
        id: string;
        title: string;
        detail: string;
        tags: Schemas.Tag[];
        announced_at: string;
    }
    export interface Tag {
        /** id */
        id: string;
        /** タグの名称 */
        name: string;
        /** html5でcolorとして扱える文字列 */
        color: string;
        tag_group: Schemas.TagGroup;
    }
    /**
     * TagGroup
     *
     * タグのグループを表すenum
     * shop_item: 商品のタググループ
     * information: お知らせのタググループ
     */
    export type TagGroup = "shop_item" | "information";
    export interface ShopItemPostParams {
        /** 商品の名前 */
        name: string;
        /** 商品のサムネイル画像のURL */
        thumbnail: string;
        /** 販売価格 */
        selling_price: number;
        /** 元の値段 */
        original_price: number;
        /** タグのidの配列 */
        tags: string[];
        /** カテゴリのidの配列 */
        categories: string[];
        /** キャンペーンのidの配列 */
        campaigns: string[];
        /** 商品の詳細 */
        details: Schemas.DetailContent[];
        /** 画像URLの配列 */
        images: string[];
        /** 関連商品のidの配列 */
        related_shop_items: string[];
    }
    export interface ShopItemPutParams {
        /** 商品の名前 */
        name?: string;
        /** 商品のサムネイル画像のURL */
        thumbnail?: string;
        /** 販売価格 */
        selling_price?: number;
        /** 元の値段 */
        original_price?: number;
        /** タグのidの配列 */
        tags?: string[];
        /** カテゴリのidの配列 */
        categories?: string[];
        /** キャンペーンのidの配列 */
        campaigns?: string[];
        /** 商品の詳細 */
        details?: Schemas.DetailContent[];
        /** 画像URLの配列 */
        images?: string[];
        /** 関連商品のidの配列 */
        related_shop_items?: string[];
    }
    export interface CategoryPostParams {
        /** カテゴリの名前 */
        name: string;
        /** カテゴリのサムネイル画像のURL */
        thumbnail: string;
    }
    export interface CategoryPutParams {
        /** カテゴリの名前 */
        name?: string;
        /** カテゴリのサムネイル画像のURL */
        thumbnail?: string;
    }
    export interface CampaignPostParams {
        /** カテゴリの名前 */
        name: string;
        /** カテゴリのサムネイル画像のURL */
        thumbnail: string;
    }
    export interface CampaignPutParams {
        /** カテゴリの名前 */
        name?: string;
        /** カテゴリのサムネイル画像のURL */
        thumbnail?: string;
    }
    export interface InformationPostParams {
        /** お知らせのタイトル */
        title: string;
        /** お知らせの詳細 */
        detail: string;
        /** お知らせのタグ */
        tags: string[];
        /** お知らせのアナウンスされた日時 */
        announced_at: string;
    }
    export interface InformationPutParams {
        /** お知らせのタイトル */
        title?: string;
        /** お知らせの詳細 */
        detail?: string;
        /** お知らせのタグ */
        tags?: string[];
        /** お知らせのアナウンスされた日時 */
        announced_at?: string;
    }
    export interface PromotionPostParams {
        /** プロモーションのタイトル */
        title: string;
        /** プロモーションの画像のURL */
        image: string;
        /** プロモーションの詳細 */
        detail: string;
        /** プロモーションのリンクのURL */
        link: string;
    }
    export interface PromotionPutParams {
        /** プロモーションのタイトル */
        title?: string;
        /** プロモーションの画像のURL */
        image?: string;
        /** プロモーションの詳細 */
        detail?: string;
        /** プロモーションのリンクのURL */
        link?: string;
    }
    export interface TagPostParams {
        /** タグの名前 */
        name: string;
        /** タグの色 */
        color: string;
        tag_group: Schemas.TagGroup;
    }
    export interface TagPutParams {
        /** タグの名前 */
        name?: string;
        /** タグの色 */
        color?: string;
    }
}
export namespace Responses { }

